# Generated by Django 3.0.2 on 2021-04-21 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limit',
            name='start_date',
            field=models.DateField(),
        ),
    ]
