# Generated by Django 3.0.2 on 2021-04-25 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("description", models.CharField(blank=True, default="", max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("PLN", "Polish Złoty"),
                            ("EUR", "Euro"),
                            ("GBP", "British Pound"),
                            ("USD", "U.S. Dollar"),
                            ("JPY", "Japanese Yen"),
                            ("CHF", "Swiss Franc"),
                            ("CAD", "Canadian Dollar"),
                        ],
                        default="EUR",
                        max_length=3,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "category",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="categories.Category"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
